apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: alpine
  name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      run: alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: alpine
    spec:
      containers:
      - image: alpine:latest
        command:
          - /bin/sh
          - "-c"
          - "echo $MOUNTED_SECRET"
          - "echo $MOUNTED_SECRET"
        imagePullPolicy: IfNotPresent
        name: alpine
        env:
        - name: password
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: username
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username              